# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d488f9d617b9ea6142a66e830f3d6cbfb194e1eb03cb9319fa8ed51c96f409a34951fdf5bb448dfde0c0512153c4dc6fbfe2c12745163d374f326b29d1e60f1

test:
  secret_key_base: 751dbe66b15c6ab168a3e3469a1f064a77c836e04db1c1638523d46c3398aa335f9b532e3101331794d50fb76fdb513517ef00cfe90b6eeca95e5e264043670d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
